"""Add user_number to users table

Revision ID: 675db83c9fad
Revises: 1cfec71e936d
Create Date: 2024-10-01 17:30:51.916759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675db83c9fad'
down_revision: Union[str, None] = '1cfec71e936d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'amount',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False)
    op.add_column('users', sa.Column('user_number', sa.String(length=256), nullable=False))
    op.drop_constraint('users_user_email_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['user_number'])
    op.drop_column('users', 'user_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_user_email_key', 'users', ['user_email'])
    op.drop_column('users', 'user_number')
    op.alter_column('payment', 'amount',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
